import type {
  ActivityLogRecord,
  CampaignLeadRecord,
  CampaignRecord,
  LeadRecord,
  SendTaskRecord,
  SequenceStepRecord,
  TelegramAccountRecord,
  TgConsoleAccountRecord,
  TgConsoleDialogRecord,
  TgConsoleMessageRecord,
  TgSendApprovalRecord,
  TgWarmedUsernameRecord,
} from '@telegram-enhancer/shared';

const workspaceId = 'demo-workspace';
const now = new Date().toISOString();

export const demoWorkspace = {
  id: workspaceId,
  name: 'Primary Workspace',
  slug: 'primary-workspace',
  timezone: 'UTC',
};

export const demoProfile = {
  id: 'demo-profile',
  workspace_id: workspaceId,
  email: 'demo@workspace.local',
  full_name: 'Workspace Admin',
  role: 'admin',
};

export const demoState: {
  leads: LeadRecord[];
  accounts: TelegramAccountRecord[];
  campaigns: CampaignRecord[];
  steps: SequenceStepRecord[];
  campaignLeads: CampaignLeadRecord[];
  sendTasks: SendTaskRecord[];
  activity: ActivityLogRecord[];
  assignments: Array<{ id: string; workspace_id: string; campaign_id: string; telegram_account_id: string; message_limit: number | null; created_at: string }>;
  botCodes: Array<any>;
  tgConsoleAccounts: TgConsoleAccountRecord[];
  tgConsoleDialogs: TgConsoleDialogRecord[];
  tgConsoleMessages: TgConsoleMessageRecord[];
  tgWarmedUsernames: TgWarmedUsernameRecord[];
  tgSendApprovals: TgSendApprovalRecord[];
} = {
  leads: [
    {
      id: 'lead-1',
      workspace_id: workspaceId,
      first_name: 'Ava',
      last_name: 'Patel',
      company_name: 'Company A',
      telegram_username: 'avapatel',
      tags: ['ICP', 'Fintech'],
      notes: 'Prefers async intros.',
      source: 'CSV import',
      owner_id: null,
      profile_picture_url: null,
      telegram_exists: null,
      telegram_checked_at: null,
      created_at: now,
    },
    {
      id: 'lead-2',
      workspace_id: workspaceId,
      first_name: 'Leo',
      last_name: 'Martin',
      company_name: 'Company A',
      telegram_username: 'leomartin',
      tags: ['CTO'],
      notes: null,
      source: 'CSV import',
      owner_id: null,
      profile_picture_url: null,
      telegram_exists: null,
      telegram_checked_at: null,
      created_at: now,
    },
    {
      id: 'lead-3',
      workspace_id: workspaceId,
      first_name: 'Mina',
      last_name: 'Cho',
      company_name: 'Company B',
      telegram_username: 'minacho',
      tags: ['Warm'],
      notes: null,
      source: 'Manual',
      owner_id: null,
      profile_picture_url: null,
      telegram_exists: null,
      telegram_checked_at: null,
      created_at: now,
    },
  ],
  accounts: [
    {
      id: 'account-1',
      workspace_id: workspaceId,
      owner_id: null,
      telegram_user_id: null,
      label: 'Outbound 01',
      telegram_username: 'team_sender_01',
      daily_limit: 25,
      is_active: true,
      profile_picture_url: null,
      created_at: now,
      restricted_until: null,
      cooldown_until: null,
      restriction_reported_at: null,
      restriction_source_text: null,
    },
    {
      id: 'account-2',
      workspace_id: workspaceId,
      owner_id: null,
      telegram_user_id: null,
      label: 'Outbound 02',
      telegram_username: 'team_sender_02',
      daily_limit: 25,
      is_active: true,
      profile_picture_url: null,
      created_at: now,
      restricted_until: null,
      cooldown_until: null,
      restriction_reported_at: null,
      restriction_source_text: null,
    },
  ],
  campaigns: [
    {
      id: 'campaign-1',
      workspace_id: workspaceId,
      name: 'Founder Warm Intro',
      description: 'Manual-send enhancer for founder outreach.',
      status: 'draft',
      timezone: 'UTC',
      send_window_start: '09:00',
      send_window_end: '18:00',
      start_date: null,
      end_date: null,
      created_at: now,
    },
  ],
  steps: [
    {
      id: 'step-1',
      workspace_id: workspaceId,
      campaign_id: 'campaign-1',
      step_order: 1,
      step_name: 'Reachout',
      delay_days: 0,
      message_template: 'Hi {First Name}, reaching out from {Company}. Thought it could make sense to connect.',
      message_variants: ['Hi {First Name}, reaching out from {Company}. Thought it could make sense to connect.'],
    },
    {
      id: 'step-2',
      workspace_id: workspaceId,
      campaign_id: 'campaign-1',
      step_order: 2,
      step_name: 'Follow Up 1',
      delay_days: 2,
      message_template: 'Quick follow-up, {First Name}. Sharing this in case {Company} is exploring outbound support.',
      message_variants: ['Quick follow-up, {First Name}. Sharing this in case {Company} is exploring outbound support.'],
    },
  ],
  campaignLeads: [],
  sendTasks: [],
  activity: [],
  assignments: [
    {
      id: 'assignment-1',
      workspace_id: workspaceId,
      campaign_id: 'campaign-1',
      telegram_account_id: 'account-1',
      message_limit: null,
      created_at: now,
    },
    {
      id: 'assignment-2',
      workspace_id: workspaceId,
      campaign_id: 'campaign-1',
      telegram_account_id: 'account-2',
      message_limit: null,
      created_at: now,
    },
  ],
  botCodes: [],
  tgConsoleAccounts: [
    {
      id: 'tg-console-account-1',
      workspace_id: workspaceId,
      profile_id: demoProfile.id,
      phone: '+1555010001',
      telegram_user_id: '70010001',
      telegram_username: 'acme_ops_01',
      display_name: 'Acme Ops 01',
      is_authenticated: true,
      status: 'authenticated',
      proxy_redacted: 'socks5://proxy-user:***@198.51.100.42:1080',
      proxy_status: 'validated',
      proxy_checked_at: now,
      last_sync_at: now,
      last_inbox_update_at: now,
      created_at: now,
      updated_at: now,
    },
  ],
  tgConsoleDialogs: [
    {
      id: 'tg-dialog-1',
      workspace_id: workspaceId,
      account_id: 'tg-console-account-1',
      telegram_dialog_id: 'user:1001',
      kind: 'user',
      title: 'David',
      username: 'david_founder',
      folder_id: 1,
      folder_name: 'All Inboxes',
      crm_folder: 'My Inbox',
      unread_count: 2,
      is_unread: true,
      is_replied: false,
      last_message_at: now,
      last_message_preview: 'I submitted the demo request form, maybe five minutes ago',
      tags: ['demo-request'],
      notes: 'Asked about the website form.',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'tg-dialog-2',
      workspace_id: workspaceId,
      account_id: 'tg-console-account-1',
      telegram_dialog_id: 'user:1002',
      kind: 'user',
      title: 'Rico',
      username: 'rico_ops',
      folder_id: 2,
      folder_name: 'Warm Replies',
      crm_folder: 'Replied',
      unread_count: 0,
      is_unread: false,
      is_replied: true,
      last_message_at: now,
      last_message_preview: 'Sounds good, send over the quick version.',
      tags: ['warm', 'operator'],
      notes: null,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'tg-dialog-3',
      workspace_id: workspaceId,
      account_id: 'tg-console-account-1',
      telegram_dialog_id: 'channel:3001',
      kind: 'channel',
      title: 'Founders Daily',
      username: 'foundersdaily',
      folder_id: 3,
      folder_name: 'Telegram Channels',
      crm_folder: 'Channels',
      unread_count: 8,
      is_unread: true,
      is_replied: false,
      last_message_at: now,
      last_message_preview: 'New thread: what changed in outbound this week?',
      tags: ['research'],
      notes: null,
      created_at: now,
      updated_at: now,
    },
  ],
  tgConsoleMessages: [
    {
      id: 'tg-message-1',
      workspace_id: workspaceId,
      account_id: 'tg-console-account-1',
      dialog_id: 'tg-dialog-1',
      telegram_message_id: '501',
      sender_name: 'David',
      is_outbound: false,
      text: 'Hey there',
      sent_at: now,
      metadata: {},
      created_at: now,
    },
    {
      id: 'tg-message-2',
      workspace_id: workspaceId,
      account_id: 'tg-console-account-1',
      dialog_id: 'tg-dialog-1',
      telegram_message_id: '502',
      sender_name: 'Acme Ops 01',
      is_outbound: true,
      text: 'Hi, this is Acme. How can we help today?',
      sent_at: now,
      metadata: {},
      created_at: now,
    },
    {
      id: 'tg-message-3',
      workspace_id: workspaceId,
      account_id: 'tg-console-account-1',
      dialog_id: 'tg-dialog-1',
      telegram_message_id: '503',
      sender_name: 'David',
      is_outbound: false,
      text: 'I submitted the demo request form, maybe five minutes ago.',
      sent_at: now,
      metadata: {},
      created_at: now,
    },
    {
      id: 'tg-message-4',
      workspace_id: workspaceId,
      account_id: 'tg-console-account-1',
      dialog_id: 'tg-dialog-2',
      telegram_message_id: '601',
      sender_name: 'Rico',
      is_outbound: false,
      text: 'Sounds good, send over the quick version.',
      sent_at: now,
      metadata: {},
      created_at: now,
    },
  ],
  tgWarmedUsernames: [
    {
      id: 'tg-warmed-1',
      workspace_id: workspaceId,
      username: 'rico_ops',
      label: 'Ops peer',
      notes: 'Known account for manual reply loops.',
      tags: ['operator', 'warm'],
      created_at: now,
    },
  ],
  tgSendApprovals: [],
};

export function demoId(prefix: string) {
  return `${prefix}-${Math.random().toString(36).slice(2, 10)}`;
}
